version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: scraped_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: